//levels

###
GET http://localhost:3000/api/levels/getall?orderby=&keyword=duy khuong&start=&limit=10
Content-Type: application/json

###
GET http://localhost:3000/api/levels/getbyid/5
Content-Type: application/json

###
POST http://localhost:3000/api/levels/create
Content-Type: application/json

{  
     
    "name":"khuong",
    "level_value": 1,
      "use_ale_min": 2,
      "use_ale_max": 3,
      "overdraft_payment_amout": 4,
      "overdraft_payment_status": "",
    "publish":"1",
     "created_at":""

}
 
###
PUT http://localhost:3000/api/levels/update/21
Content-Type: application/json

{   
    "name":"khuong duy",
    "level_value": 1,
      "use_ale_min": 2,
      "use_ale_max": 3,
      "overdraft_payment_amout": 4,
      "overdraft_payment_status": "",
    "publish":"1",
    "updated_at":""
     
  
}

###
PUT http://localhost:3000/api/levels/update-publish/20
Content-Type: application/json

{
    "publish": ""
}



###
DELETE http://localhost:3000/api/levels/delete/20

