//weight

###
GET http://localhost:3001/api/weight/getall?orderby=&keyword=&limit=&start=
Content-Type: application/json

###
GET http://localhost:3001/api/weight/getbyid/3
Content-Type: application/json

###
POST http://localhost:3001/api/weight/create
Content-Type: application/json

{   
    "name":"Bò",
    "min_value":"20",
    "max_value":"80",
    "publish":"1"
}

###
PUT http://localhost:3001/api/weight/update/1
Content-Type: application/json

{   
    "name":"Heo Heo",
    "min_value":"13.5",
    "max_value":"21.4",
    "publish":"1",
    "sort": "2"
}

###
PUT http://localhost:3001/api/weight/update-publish/1
Content-Type: application/json

{
    "publish": "1"
}

###
PUT http://localhost:3001/api/weight/update-sort/2
Content-Type: application/json



###
DELETE http://localhost:3001/api/weight/delete/3

